#!/usr/bin/env bash

source ./ire.functions.sh

parse_args()
{
  case "$1" in
    commit) commit
    ;;
    daoTest) daoTest
    ;;
    integrationTest) integrationTest
    ;;
    g) echo "g" && gradle "${@:2}"
    ;;
    drs) drs
    ;;
    package) gradle clean && package
    ;;
    *) usages
      ;;
  esac
}

main()
{
  ROOT_DIR=$(pwd)
  cd $ROOT_DIR
  ./bootstrap.sh
  export JAVA_HOME=opt/jdk/Contents/Home
  echo "Setting Java Home to $JAVA_HOME"
  parse_args $@
}

main $@

