#!/usr/bin/env bash

source ./ire.functions.sh

parse_args()
{
  case "$1" in
    commit) commit
    ;;
    daoTest) daoTest
    ;;
    integrationTest) integrationTest
    ;;
    allTests) allTests
      ;;
    g) echo "g" && gradle "${@:2}"
    ;;
    drs) drs
    ;;
    package) gradle clean && package
    ;;
    *) usages
      ;;
  esac
}

main()
{
  ROOT_DIR=$(pwd)
  OPT_DIR=$ROOT_DIR/opt
  cd $ROOT_DIR
  ./bootstrap.sh
  export JAVA_HOME=${OPT_DIR}/jdk/Contents/Home
  export PATH=${OPT_DIR}/node/bin:${OPT_DIR}/pnpm:${OPT_DIR}/awscli/bin:${OPT_DIR}/granted:${PATH}
  echo "Setting Java Home to $JAVA_HOME"
  parse_args $@
}

main $@

